// Generated by CoffeeScript 1.10.0
var assert;

assert = chai.assert;

describe('deck', function() {
  var deck, hand;
  deck = null;
  hand = null;
  beforeEach(function() {
    deck = new Deck();
    return hand = deck.dealPlayer();
  });
  describe('hit', function() {
    return it('should give the last card from the deck', function() {
      assert.strictEqual(deck.length, 50);
      assert.strictEqual(deck.last(), hand.hit());
      return assert.strictEqual(deck.length, 49);
    });
  });
  return describe('stand', function() {
    return it('should stand', function() {
      assert.strictEqual(deck.length, 50);
      hand.stand();
      return assert.strictEqual(deck.length, 50);
    });
  });
});
