// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

window.App = (function(superClass) {
  extend(App, superClass);

  function App() {
    return App.__super__.constructor.apply(this, arguments);
  }

  App.prototype.initialize = function() {
    var deck;
    this.set('deck', deck = new Deck());
    this.set('playerHand', deck.dealPlayer());
    this.set('dealerHand', deck.dealDealer());
    this.get('playerHand').on('roundOver', (function(_this) {
      return function() {
        return _this.dealNewHand();
      };
    })(this));
    this.get('playerHand').on('stand', (function(_this) {
      return function() {
        return _this.dealerPlay();
      };
    })(this));
    return this.get('deck').on('outOfCards', (function(_this) {
      return function() {
        return initialize();
      };
    })(this));
  };

  App.prototype.dealNewHand = function() {
    console.log('next round******************');
    this.set('playerHand', this.get('deck').dealPlayer());
    this.set('dealerHand', this.get('deck').dealDealer());
    return this.trigger('newStuff', this);
  };

  App.prototype.dealerPlay = function() {
    var ref;
    console.log('inside dealerPlay ^^^^^^^^^^^^^^^^');
    while (!(this.get('dealerHand').scores()[0] >= 17)) {
      this.get('dealerHand').hit();
    }
    if (this.get('playerHand').scores()[0] === this.get('dealerHand').scores()[0]) {
      alert('Push');
    } else if ((this.get('playerHand').scores()[0] < (ref = this.get('dealerHand').scores()[0]) && ref < 22)) {
      alert('Dealer wins');
      console.log('dealer wins');
    } else {
      alert('You win!');
      console.log('you win');
    }
    return this.trigger('newStuff', this);
  };

  return App;

})(Backbone.Model);
