// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

window.App = (function(superClass) {
  var scores;

  extend(App, superClass);

  function App() {
    return App.__super__.constructor.apply(this, arguments);
  }

  scores = {
    player: 0,
    dealer: 0,
    pushes: 0,
    busts: 0
  };

  App.prototype.initialize = function() {
    var deck;
    this.set('deck', deck = new Deck());
    this.set('playerHand', deck.dealPlayer());
    this.set('dealerHand', deck.dealDealer());
    this.set('scores', scores);
    this.get('playerHand').on('roundOver', (function(_this) {
      return function() {
        _this.removeOldHands(_this.get('playerHand'));
        _this.removeOldHands(_this.get('dealerHand'));
        scores['busts'] += 1;
        return _this.scoreKeeper();
      };
    })(this));
    this.get('playerHand').on('stand', (function(_this) {
      return function() {
        return _this.dealerPlay();
      };
    })(this));
    return this.get('deck').on('outOfCards', (function(_this) {
      return function() {
        return initialize;
      };
    })(this));
  };

  App.prototype.removeOldHands = function(hand) {
    var cardsInHand;
    while (!(cardsInHand < 1)) {
      cardsInHand = hand.length;
      hand.pop();
    }
    this.dealNewHands(hand);
    return this.trigger('newStuff', this);
  };

  App.prototype.dealNewHands = function(hand) {
    if (hand.isDealer) {
      hand.hit().flip();
    } else {
      hand.hit();
    }
    hand.hit();
    return this.trigger('newStuff', this);
  };

  App.prototype.dealerPlay = function() {
    debugger;
    while (!(this.get('dealerHand').scores()[0] >= 17)) {
      this.get('dealerHand').hit();
      console.log(this.get('dealerHand').scores()[0]);
    }
    return this.scoreKeeper();
  };

  App.prototype.scoreKeeper = function() {
    var ref;
    if (this.get('playerHand').scores()[0] === this.get('dealerHand').scores()[0]) {
      alert('Push');
      scores['pushes'] += 1;
    } else if ((this.get('playerHand').scores()[0] < (ref = this.get('dealerHand').scores()[0]) && ref < 22)) {
      alert('Dealer wins');
      scores['dealer'] += 1;
    } else {
      alert('You win!');
      scores['player'] += 1;
    }
    this.removeOldHands(this.get('playerHand'));
    return this.removeOldHands(this.get('dealerHand'));
  };

  return App;

})(Backbone.Model);
